$engine: 3
$onesync: on
name: AMERICAN STORIES
author: Enjoy_it
description: AMERICAN STORIES SERVIDOR BASE!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[CFX-DEFAULT]

  - action: remove_path
    path: ./resources/[CFX-DEFAULT]/[gameplay]/chat

  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/esx-framework/esx-recipes
    ref: legacy
    dest: ./tmp/recipe

  # Connect to the database
  - action: connect_database

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[MAPS]/bob74_ipl

  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    ref: main
    dest: ./tmp/addons/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    ref: main
    dest: ./tmp/addons/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    ref: main
    dest: ./tmp/addons/esx_datastore

  - action: download_github
    src: https://github.com/esx-framework/esx_service
    ref: main
    dest: ./tmp/addons/esx_service

  - action: download_github
    src: https://github.com/esx-framework/esx_rpchat
    ref: main
    dest: ./tmp/addons/esx_rpchat

  - action: download_github
    src: https://github.com/esx-framework/esx_cruisecontrol
    ref: main
    dest: ./tmp/addons/esx_cruisecontrol

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    ref: main
    dest: ./tmp/addons/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_optionalneeds
    ref: main
    dest: ./tmp/addons/esx_optionalneeds

  - action: waste_time # Prevent GitHub throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    ref: main
    dest: ./tmp/addons/esx_society

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    ref: main
    dest: ./tmp/addons/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    ref: main
    dest: ./tmp/addons/esx_status

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[CORE]

  - action: move_path
    src: ./tmp/addons/
    dest: ./resources/[ESX]

  ## OX Framework Dependencies

  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip

  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[OX]

  - action: download_file
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
    path: ./tmp/ox_inventory.zip

  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources/[OX]

  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip

  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources/[OX]

  - action: download_file
    url: https://github.com/overextended/ox_doorlock/releases/latest/download/ox_doorlock.zip
    path: ./tmp/ox_doorlock.zip

  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./resources/[OX]

  - action: download_github
    src: https://github.com/overextended/ox_fuel
    ref: main
    dest: ./resources/[OX]/ox_fuel

  - action: download_github
    src: https://github.com/overextended/ox_target
    ref: main
    dest: ./resources/[OX]/ox_target

  - action: waste_time # Prevent GitHub throttling
    seconds: 5

  ## ADDONS

  - action: download_file
    url: https://github.com/Renewed-Scripts/Renewed-Banking/releases/latest/download/Renewed-Banking.zip
    path: ./tmp/Renewed-Banking.zip

  - action: unzip
    src: ./tmp/Renewed-Banking.zip
    dest: ./resources/[ADDONS]

  # illenium-appearance

  - action: download_file
    path: ./tmp/illenium-appearance.zip
    url: https://github.com/iLLeniumStudios/illenium-appearance/releases/latest/download/illenium-appearance.zip
  - action: unzip
    dest: ./resources/[ADDONS]
    src: ./tmp/illenium-appearance.zip

  # dx_hud

  - action: download_github
    src: https://github.com/0xDEMXN/dx_hud
    ref: main
    dest: ./resources/[OX]/dx_hud

  # Lunar garage

  - action: download_github
    src: https://github.com/Lunar-Scripts/lunar_garage
    ref: main
    dest: ./resources/[ADDONS]/lunar_garage

  # Lunar jobcentre

  - action: download_github
    src: https://github.com/Lunar-Scripts/lunar_jobcentre
    ref: main
    dest: ./resources/[ADDONS]/lunar_jobcentre

  # mana audio

  - action: download_github
    src: https://github.com/Manason/mana_audio
    ref: main
    dest: ./resources/[ADDONS]/mana_audio

  # loadingscreen

  - action: download_github
    src: https://github.com/DokaDoka/pe-basicloading
    ref: ox
    dest: ./resources/[DEPENDENCIAS]/pe-basicloading

  - action: replace_string
    mode: all_vars
    file:
      - ./resources/[DEPENDENCIAS]/pe-basicloading/web/config.js

  - action: waste_time # Prevent GitHub throttling
    seconds: 5

  ## DEPENDENCIAS

  - action: download_file
    url: https://github.com/project-error/screenshot-basic/releases/latest/download/screenshot-basic.zip
    path: ./tmp/screenshot-basic.zip

  - action: unzip
    src: ./tmp/screenshot-basic.zip
    dest: ./resources/[DEPENDENCIAS]/screenshot-basic

  # VOICE
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[voice]/pma-voice

  - action: download_github
    src: https://github.com/Scullyy/scully_emotemenu
    ref: main
    dest: ./resources/[DEPENDENCIAS]/scully_emotemenu

  - action: waste_time # Prevent GitHub throttling
    seconds: 5

  - action: download_github
    src: https://github.com/ultrahacx/ultra-voltlab
    ref: main
    dest: ./resources/[DEPENDENCIAS]/ultra-voltlab

  - action: download_github
    src: https://github.com/BaziForYou/MugShotBase64
    ref: main
    dest: ./resources/[DEPENDENCIAS]/MugShotBase64

  - action: download_file
    url: https://raw.githubusercontent.com/BaziForYou/MugShotBase64/main/README.md
    path: ./resources/[DEPENDENCIAS]/MugShotBase64/README.md

  - action: download_file
    url: https://raw.githubusercontent.com/BaziForYou/MugShotBase64/main/LICENSE.md
    path: ./resources/[DEPENDENCIAS]/MugShotBase64/LICENSE.md

  - action: download_file
    url: https://github.com/dsheedes/cd_easytime/releases/latest/download/cd_easytime.zip
    path: ./tmp/cd_easytime.zip

  - action: unzip
    src: ./tmp/cd_easytime.zip
    dest: ./resources/[DEPENDENCIAS]/cd_easytime

  - action: download_github
    src: https://github.com/Xogy/xsound
    ref: master
    dest: ./resources/[DEPENDENCIAS]/xsound

  ## PLUGINS

  # shark leotools

  - action: download_github
    src: https://github.com/GeneralShark05/shark-leotools
    ref: main
    dest: ./resources/[PLUGGINS]/shark-leotools 

  # Lunar fishing

  - action: download_github
    src: https://github.com/Lunar-Scripts/lunar_fishing
    ref: main
    dest: ./resources/[PLUGGINS]/lunar_fishing

  # mana hunting

  - action: download_github
    src: https://github.com/Manason/mana_hunting
    ref: master
    dest: ./resources/[PLUGGINS]/mana_hunting

  - action: download_github
    src: https://github.com/Enjoy1982/base-server/esxLogo.png
    ref: main
    dest: ./tmp/esxLogo.png

  - action: move_path
    src: ./tmp/esxLogo.png
    dest: ./esxLogo.png


  - action: download_github
    src: https://github.com/Enjoy1982/base-server/server.cfg
    ref: main
    dest: ./tmp/server.cfg

  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg


  ## Cleanup

  - action: remove_path
    path: ./tmp
